### ISSUE TITLE
Owlery docker container errors out from log4j

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#130]
Trying to start Owlery from the Docker container I get the following error, because of a missing or incorrect `log4j` configuration.  I *did* read the FAQ the error cites but ... it is not at all helpful.  In particular, it says 

  > Knowing the appropriate location to place log4j.properties or log4j.xml requires understanding the search strategy of the class loader in use. 

A little googling suggests that I might need to put something in the `akka` configuration, but I am not sure what.  But I'm not sure that is right, since the error message just mentions jena.

```
docker run --rm -p 8080:8080 -v /Users/rpg/projects/xplan/container-ontology/owl/:/srv/owl -v /Users/rpg/projects/xplan/container-ontology/owl/owlery-conf:/srv/config phenoscape/owlery:latest
log4j:WARN No appenders could be found for logger (org.apache.jena.util.FileManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.phenoscape.owlery.Main$.initializeReasoners(Main.scala:62)
	at org.phenoscape.owlery.Main$.delayedEndpoint$org$phenoscape$owlery$Main$1(Main.scala:64)
	at org.phenoscape.owlery.Main$delayedInit$body.apply(Main.scala:19)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at org.phenoscape.owlery.Main$.main(Main.scala:19)
	at org.phenoscape.owlery.Main.main(Main.scala)
Caused by: com.typesafe.config.ConfigException$IO: /srv/conf/application.conf: java.io.FileNotFoundException: /srv/conf/application.conf (No such file or directory)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:190)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:790)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:51)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:261)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:258)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:66)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:93)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:258)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:234)
	at org.phenoscape.owlery.Owlery$.<clinit>(Owlery.scala:18)
	... 15 more
Caused by: java.io.FileNotFoundException: /srv/conf/application.conf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.java:629)
	at com.typesafe.config.impl.Parseable.reader(Parseable.java:99)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:233)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	... 27 more
make: *** [server] Error 1
```

In case it is helpful, my configuration file is as follows:

```
akka {
  loglevel = INFO
}

akka.http.server {
  request-timeout = infinite
  idle-timeout = infinite
}

owlery {
    port = 8080
    host = localhost
    kbs = [
        {
            name = strateos-catalog
            location = "/srv/owl/strateos-catalog-individuals.ttl"
            reasoner = structural
        }
    ]
}
```

**Comment by rpgoldman** [comment]
*Blush* I didn't read the message carefully enough.  There seems to be something wrong with mounting my conf file.
