### ISSUE TITLE
Reasoner results from Owlery and Protege different

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#165]
I have set up an Owlery configuration using the `hermit` verification setting, and when I try to load my ontology, it is rejected as inconsistent:

```
Exception in thread "main" org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology
	at org.semanticweb.HermiT.Reasoner.throwInconsistentOntologyExceptionIfNecessary(Reasoner.java:2296)
	at org.semanticweb.HermiT.Reasoner.checkPreConditions(Reasoner.java:2288)
	at org.semanticweb.HermiT.Reasoner.precomputeInferences(Reasoner.java:581)
	at org.phenoscape.owlery.Main$.$anonfun$initializeReasoners$1(Main.scala:81)
	at org.phenoscape.owlery.Main$.$anonfun$initializeReasoners$1$adapted(Main.scala:81)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at org.phenoscape.owlery.Main$.initializeReasoners(Main.scala:81)
	at org.phenoscape.owlery.Main$.delayedEndpoint$org$phenoscape$owlery$Main$1(Main.scala:83)
	at org.phenoscape.owlery.Main$delayedInit$body.apply(Main.scala:23)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.phenoscape.owlery.Main$.main(Main.scala:23)
	at org.phenoscape.owlery.Main.main(Main.scala)
```

But when I load the same ontology into Protege, set the reasoner to HermiT, I am told that my ontology is coherent and consistent.  Using FaCT or Pellet gives the same result.

I have only one clue: when I look at the logs I see this line describing one of my ontologies:

```
2021-09-24 22:08:14.398 [main] DEBUG TripleLogger    Loaded OntologyID(OntologyIRI(<https://raw.githubusercontent.com/rpgoldman/container-ontology/main/owl/strateos-catalog.ttl>) VersionIRI(<null>))
2021-09-24 22:08:14.400 [main] DEBUG RioParserImpl$RioParserRDFHandler    owlParse: timing=89
2021-09-24 22:08:14.400 [main] DEBUG RioParserImpl    rioParse: timing=90
2021-09-24 22:08:14.411 [main] DEBUG TripleLogger    Total number of triples: 6
```

This file is 1968 lines of turtle.  This is a pretty whitespace-heavy notation, but there should *definitely* be more than 6 total triples in there.  Is there any chance we are losing something here?  That still leaves me at a loss, though: OWL is monotonic, so I don't think there's any way getting a subset of a set of ontologies could be inconsistent if the superset is consistent.

Is there anything I could do to try to dope this out?

Thanks!

**Comment by rpgoldman** [comment]
I have narrowed it down to the following ontology file, which I can load into Protege, but that I cannot load successfully into Owlery.  Hoping this suggests something.

[bbn-plate-catalog.ttl.txt](https://github.com/phenoscape/owlery/files/7228664/bbn-plate-catalog.ttl.txt)

**Comment by rpgoldman** [comment]
OK, I have found the problem, but I have no idea why this fixes it.

If I take out the language-tagged string literals -- e.g., replace `"Corning"@en` with `"Corning"` in the datatype properties, Owlery is happy with my ontology.  Protege is fine with having them in there.

Are the language-tagged strings only allowable in annotation properties (i.e., is Protege wrong?) or should these be acceptable (i.e., is Owlery wrong?)?

Since AFAIK both are built on OWLAPI, I have no idea why this divergence would happen. Perhaps a difference in how the reasoner is invoked?
