### ISSUE TITLE
Does Owlery support datatype constraints in its queries?

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#167]
I have tried to query with this (somewhat cumbersome) formula:

```
(<https://sift.net/container-ontology/container-ontology#wellVolume> some (<http://www.ontology-of-units-of-measure.org/resource/om-2/hasNumericalValue> only owl:real[>= "200"^^owl:real]))
```

and Owlery is giving me a 500 error.  When I look at the logs, I see this:

```
[ERROR] [10/05/2021 21:58:17.865] [Main-akka.actor.default-dispatcher-34] [akka.actor.ActorSystemImpl(Main)] Error during processing of request: 'Literal "200"^^<http://www.w3.org/2002/07/owl#real> is malformed'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
org.semanticweb.HermiT.datatypes.MalformedLiteralException: Literal "200"^^<http://www.w3.org/2002/07/owl#real> is malformed
	at org.semanticweb.HermiT.datatypes.owlreal.OWLRealDatatypeHandler.parseLiteral(OWLRealDatatypeHandler.java:118)
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.parseLiteral(DatatypeRegistry.java:105)
	at org.semanticweb.HermiT.model.Constant.create(Constant.java:111)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.visit(OWLClausification.java:898)
	at uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression.accept(OWLLiteralImplNoCompression.java:270)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.visit(OWLClausification.java:876)
	at uk.ac.manchester.cs.owl.owlapi.OWLDatatypeRestrictionImpl.accept(OWLDatatypeRestrictionImpl.java:136)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.convertDataRange(OWLClausification.java:820)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.visit(OWLClausification.java:850)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataComplementOfImpl.accept(OWLDataComplementOfImpl.java:121)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.convertDataRange(OWLClausification.java:820)
	at org.semanticweb.HermiT.structural.OWLClausification$NormalizedAxiomClausifier.visit(OWLClausification.java:639)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataSomeValuesFromImpl.accept(OWLDataSomeValuesFromImpl.java:82)
	at org.semanticweb.HermiT.structural.OWLClausification.clausify(OWLClausification.java:235)
	at org.semanticweb.HermiT.Reasoner.createDeltaDLOntology(Reasoner.java:2194)
	at org.semanticweb.HermiT.Reasoner.getTableau(Reasoner.java:2039)
	at org.semanticweb.HermiT.Reasoner.getHierarchyNode(Reasoner.java:964)
	at org.semanticweb.HermiT.Reasoner.getInstances(Reasoner.java:1765)
	at org.phenoscape.owlery.Knowledgebase.$anonfun$queryInstances$1(Knowledgebase.scala:72)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

This is a HermiT problem: when I test this using Protege, I get an error with HermiT as reasoner, but everything is fine with Fact++.  Any idea what is going wrong here?

**Comment by rpgoldman** [comment]
Oh, yes, it's coming back to me now. I tried resetting the reasoner to `jfact` and `jfact` thinks my ontology is inconsistent.  Neither Hermit nor Fact++ (which I assume is the C++ version of Fact) agree with this.

Unfortunately, my ontology will provide no useful inferences if I am limited to EL.  Any suggestions for what I might do?

Any chance there are more up-to-date versions of either Hermit or JFact that could be incorporated?

**Comment by balhoff** [comment]
I haven't done much with literals in OWL, but could it be something to do with what it says here? https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Real_Numbers.2C_Decimal_Numbers.2C_and_Integers

"The owl:real datatype does not directly provide any lexical forms."

Could you leave off the datatype? e.g. `200` instead of `"200"^^owl:real`? Or use `xsd:decimal` instead?

**Comment by balhoff** [comment]
Another clue: https://github.com/protegeproject/protege/issues/37
