### ISSUE TITLE
Configuration syntax change in latest Docker image?

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#199]
When I run with the latest Owlery docker image, using this command line:

    docker run --rm --env JAVA_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -Dlogback.configurationFile=/srv/conf/logback.xml'  -p 8080:8080 -v /Users/rpg/projects/xplan/container-ontology/owl//server-files:/srv/owl -v /Users/rpg/projects/xplan/container-ontology/owl/owlery-conf:/srv/conf phenoscape/owlery :latest 2>&1 | tee server.log

I now get the following error:

````
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.phenoscape.owlery.Main$.initializeReasoners(Main.scala:82)
	at org.phenoscape.owlery.Main$.delayedEndpoint$org$phenoscape$owlery$Main$1(Main.scala:84)
	at org.phenoscape.owlery.Main$delayedInit$body.apply(Main.scala:24)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.phenoscape.owlery.Main$.main(Main.scala:24)
	at org.phenoscape.owlery.Main.main(Main.scala)
Caused by: com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'owlery.kbs'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:262)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:442)
	at com.typesafe.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:460)
	at com.typesafe.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:465)
	at org.phenoscape.owlery.Owlery$.<clinit>(Owlery.scala:23)
	... 15 more
```

This is my configuration, which used to work:
```
akka {
  loglevel = DEBUG
  log-config-on-start = on
  loggers = ["akka.event.Logging$DefaultLogger"]
}

akka.http.server {
  request-timeout = infinite
  idle-timeout = infinite
}

owlery {
    loglevel = DEBUG
    port = 8080
    host = localhost
	kbs = [
		{
			name = sd2e-container-catalogs
			location = "/srv/owl/all-catalogs.ttl"
			reasoner = hermit
                        catalog = "/srv/owl/owlery-catalog.xml"
		}
	]
}
```

**Comment by balhoff** [comment]
Strange—it says "No configuration setting found for key 'owlery.kbs'", but you do seem to have that key.

**Comment by rpgoldman** [comment]
Aha! I have somewhat figured this out.  When I add ` -Dconfig.file=/srv/conf/application.conf` to the `JAVA_ARGS`, the new docker image works.  For some reason, when I was running before, owlery automagically found this configuration file.  Whew!
